<a href="https://colab.research.google.com/github/monalbhuva/Pytorch/blob/main/Dataset_%26_DataLoader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
from sklearn.datasets import make_classification
import torch

In [11]:
X, y = make_classification(n_samples=10,
                           n_features=2,
                           n_informative=2,
                           n_redundant=0,
                           n_classes=2,
                           random_state=42)

In [12]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [13]:
X.shape

(10, 2)

In [14]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [15]:
y.shape

(10,)

In [16]:
X = torch.tensor(X , dtype=torch.float32)
y = torch.tensor(y , dtype=torch.long)

In [19]:
from torch.utils.data import Dataset, DataLoader

In [20]:
class CustomDataset(Dataset):

  def __init__(self, features, labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self, index):
    return self.features[index], self.labels[index]

In [21]:
dataset = CustomDataset(X, y)

In [23]:
len(dataset)

10

In [24]:
dataset[0]

(tensor([ 1.0683, -0.9701]), tensor(1))

In [25]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [26]:
for batch_features, batch_labels in dataloader:
  print(batch_features)
  print(batch_labels)
  print("=" * 50)

tensor([[-2.8954,  1.9769],
        [-1.9629, -0.9923]])
tensor([0, 0])
tensor([[ 1.7273, -1.1858],
        [ 1.8997,  0.8344]])
tensor([1, 1])
tensor([[ 1.0683, -0.9701],
        [-0.5872, -1.9717]])
tensor([1, 0])
tensor([[-1.1402, -0.8388],
        [ 1.7774,  1.5116]])
tensor([0, 1])
tensor([[-0.9382, -0.5430],
        [-0.7206, -0.9606]])
tensor([1, 0])


In [27]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [28]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [29]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [30]:
df.head()

diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

In [31]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [32]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [33]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [34]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [35]:
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):

  def __init__(self, features, labels):

    self.features = features
    self.labels = labels

  def __len__(self):

    return len(self.features)

  def __getitem__(self, idx):

    return self.features[idx], self.labels[idx]



In [36]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [37]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

In [38]:
import torch.nn as nn


class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [39]:
learning_rate = 0.1
epochs = 25

In [40]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loss function
loss_function = nn.BCELoss()

In [41]:

# define loop
for epoch in range(epochs):

  for batch_features, batch_labels in train_loader:

    # forward pass
    y_pred = model(batch_features)

    # loss calculate
    loss = loss_function(y_pred, batch_labels.view(-1,1))

    # clear gradients
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    # parameters update
    optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.16300979256629944
Epoch: 2, Loss: 0.13211731612682343
Epoch: 3, Loss: 0.29966649413108826
Epoch: 4, Loss: 0.12932716310024261
Epoch: 5, Loss: 0.011152945458889008
Epoch: 6, Loss: 0.05879517272114754
Epoch: 7, Loss: 0.06689964234828949
Epoch: 8, Loss: 0.1072884276509285
Epoch: 9, Loss: 0.016443515196442604
Epoch: 10, Loss: 0.3468096852302551
Epoch: 11, Loss: 0.0716128721833229
Epoch: 12, Loss: 0.04350484162569046
Epoch: 13, Loss: 0.06138954684138298
Epoch: 14, Loss: 0.06259088963270187
Epoch: 15, Loss: 0.1897563487291336
Epoch: 16, Loss: 0.049363426864147186
Epoch: 17, Loss: 0.024361027404665947
Epoch: 18, Loss: 0.5178362727165222
Epoch: 19, Loss: 0.06142878904938698
Epoch: 20, Loss: 0.0512949638068676
Epoch: 21, Loss: 0.013158225454390049
Epoch: 22, Loss: 0.0455133318901062
Epoch: 23, Loss: 0.011576062999665737
Epoch: 24, Loss: 0.007288135122507811
Epoch: 25, Loss: 0.30333855748176575


In [42]:
# Model evaluation using test_loader
model.eval()  # Set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        # Forward pass
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.8).float()  # Convert probabilities to binary predictions

        # Calculate accuracy for the current batch
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

# Calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')


Accuracy: 0.9688
