<a href="https://colab.research.google.com/github/monalbhuva/Pytorch/blob/main/Pytorch_NN_Module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [124]:
# Create Model Class

import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, feature):
    out = self.linear(feature)
    out = self.sigmoid(out)

    return out


In [125]:
# Create Dataset
features = torch.rand(10,5)

# Create Model
model = Model(features.shape[1])

# Call model for forward pass
model(features)

tensor([[0.4920],
        [0.5715],
        [0.4759],
        [0.5350],
        [0.5174],
        [0.5747],
        [0.5177],
        [0.5546],
        [0.5364],
        [0.4720]], grad_fn=<SigmoidBackward0>)

In [126]:
# Show Model Weight
model.linear.weight

Parameter containing:
tensor([[-0.1164, -0.3815,  0.1952,  0.1052,  0.2438]], requires_grad=True)

In [127]:
model.linear.bias

Parameter containing:
tensor([0.1375], requires_grad=True)

In [128]:
!pip install torchinfo

In [129]:
from torchinfo import summary

summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

###Add Hidden Layer

In [130]:
# Create Model Class

import torch
import torch.nn as nn

class Model_with_hidden_Layer(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, feature):
    out = self.linear1(feature)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

In [131]:
# Create Dataset
features = torch.rand(10,5)

# Create Model
model = Model_with_hidden_Layer(features.shape[1])

# Call model for forward pass
model(features)

tensor([[0.3295],
        [0.3191],
        [0.3347],
        [0.3288],
        [0.3210],
        [0.3374],
        [0.3269],
        [0.3256],
        [0.3220],
        [0.3288]], grad_fn=<SigmoidBackward0>)

In [132]:
# Show Model Weight
model.linear2.weight

Parameter containing:
tensor([[-0.0411, -0.4097, -0.2765]], requires_grad=True)

In [133]:
model.linear2.bias

Parameter containing:
tensor([-0.5609], requires_grad=True)

In [134]:
from torchinfo import summary

summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model_with_hidden_Layer                  [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

###Add Sequential

In [135]:
# Create Model Class

import torch
import torch.nn as nn

class Model_with_hidden_Layer_sequential(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, feature):
    out = self.network(feature)

    return out

In [136]:
# Create Dataset
features = torch.rand(10,5)

# Create Model
model = Model_with_hidden_Layer_sequential(features.shape[1])

# Call model for forward pass
model(features)

tensor([[0.5476],
        [0.5913],
        [0.5540],
        [0.5901],
        [0.5548],
        [0.5811],
        [0.5673],
        [0.5682],
        [0.5555],
        [0.5571]], grad_fn=<SigmoidBackward0>)

### Implement Pipline Using NN

In [137]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [138]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [139]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [140]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [141]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [142]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [143]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [167]:
X_train_tensor = torch.from_numpy(X_train).double()
X_test_tensor = torch.from_numpy(X_test).double()
y_train_tensor = torch.from_numpy(y_train).double()
y_test_tensor = torch.from_numpy(y_test).double()

In [176]:
class MySimpleNN(nn.Module):

  def __init__(self,num_feature):
    super().__init__()
    self.linear = nn.Linear(num_feature, 1)
    self.sigmoid = nn.Sigmoid()


  def forward(self, feature):
    out = self.linear(feature)
    out = self.sigmoid(out)
    return out

In [177]:
loss_function = nn.BCELoss()

In [178]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [179]:
learning_rate = 0.1
epochs = 25

In [180]:
# Create Model

models = MySimpleNN(X_train_tensor.shape[1])
models = models.double()

# Define Optimizer
optimizer = torch.optim.SGD(models.parameters(), lr=learning_rate)


# Define Loop

for epoch in range(epochs):

  # Forward Pass
  y_pred = models(X_train_tensor)

  # Loss Calculate
  loss = loss_function(y_pred, y_train_tensor.view(-1, 1))

  # Zero Gradients
  optimizer.zero_grad()

  # Backward Pass
  loss.backward()

  # Parameters Update
  optimizer.step()

  # Print Loss in each Epoch
  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.5039698538045162
Epoch: 2, Loss: 0.43159596053857485
Epoch: 3, Loss: 0.38412860541245214
Epoch: 4, Loss: 0.3501437844869408
Epoch: 5, Loss: 0.32431805187342644
Epoch: 6, Loss: 0.3038486099380075
Epoch: 7, Loss: 0.2871135085167544
Epoch: 8, Loss: 0.2731038642035286
Epoch: 9, Loss: 0.2611557828435532
Epoch: 10, Loss: 0.2508123236048449
Epoch: 11, Loss: 0.24174728532075737
Epoch: 12, Loss: 0.23372065303743736
Epoch: 13, Loss: 0.2265512858144073
Epoch: 14, Loss: 0.2200994905098668
Epoch: 15, Loss: 0.21425551801316983
Epoch: 16, Loss: 0.2089317432982586
Epoch: 17, Loss: 0.20405721241179647
Epoch: 18, Loss: 0.19957375380091683
Epoch: 19, Loss: 0.19543314945108012
Epoch: 20, Loss: 0.19159503994602112
Epoch: 21, Loss: 0.1880253478484757
Epoch: 22, Loss: 0.18469507369424792
Epoch: 23, Loss: 0.18157936422678883
Epoch: 24, Loss: 0.17865678251805653
Epoch: 25, Loss: 0.1759087298705096


In [181]:
models.linear.weight

Parameter containing:
tensor([[ 0.3253,  0.2765,  0.2764,  0.3403,  0.2403,  0.1344,  0.1400,  0.1511,
          0.0246, -0.2311,  0.1986, -0.0155,  0.2268,  0.2558,  0.0344,  0.1317,
         -0.0692, -0.0202, -0.0920,  0.0377,  0.1479,  0.0556,  0.1589,  0.3776,
          0.1545,  0.0039,  0.1959,  0.3116,  0.1178,  0.1331]],
       dtype=torch.float64, requires_grad=True)

In [182]:
# model evaluation
with torch.no_grad():
  y_pred = models.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5418590307235718
