<a href="https://colab.research.google.com/github/monalbhuva/Pytorch/blob/main/Tensor_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.8.0+cu126


In [2]:
if torch.cuda.is_available():
  print("GPU is Available")
  print(f"Using GPU : {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not Available, Using CPU.")

GPU is Available
Using GPU : Tesla T4


###Create Tensor

In [4]:
# using empty
a = torch.empty(2,3)

In [5]:
# check Type
type(a)

torch.Tensor

In [6]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# using random
torch.rand(2,3)

tensor([[0.5295, 0.9424, 0.0082],
        [0.4472, 0.2421, 0.7328]])

In [9]:
#using seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
# using tensor

torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
# other way

# arange
print("using arange ->",torch.arange(0,10))

#using linsapce
print("using linspace ->",torch.linspace(0,10,10))

#using eye
print("using eye ->",torch.eye(5))

# using full
print("using full ->",torch.full((3,3),5))

using arange -> tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


###Tensor Shapes

In [13]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
x.shape

torch.Size([2, 3])

In [15]:
torch.empty_like(x)

tensor([[              0,       252342144,       258303744],
        [134915468530128,               0,               0]])

In [16]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [17]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [23]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

###Tensor Data Type

In [20]:
# find data type
x.dtype

torch.int64

In [21]:
# assign data type
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [22]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

###Mathematical Operation

####1. Scaler

In [25]:
x = torch.rand(2,3)
x

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])

In [26]:
# Addition
x + 2

# substraction
x - 2

# multiplication
x * 2

# division
x / 2

# power
x ** 2

tensor([[0.0501, 0.0914, 0.0318],
        [0.6787, 0.3089, 0.9546]])

####2.Element wise operation

In [27]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003]])
tensor([[0.5277, 0.2472, 0.7909],
        [0.4235, 0.0169, 0.2209]])


In [30]:
# add
a + b

# sub
a - b

# multiplication
a * b

# div
a / b

# power
a ** b

# mod
a % b

tensor([[0.4440, 0.2063, 0.7445],
        [0.0657, 0.0060, 0.0377]])

In [33]:
# abc

c = torch.tensor([1,2,-3,4,-5,-6])
torch.abs(c)


tensor([1, 2, 3, 4, 5, 6])

In [34]:
torch.neg(c)

tensor([-1, -2,  3, -4,  5,  6])

In [36]:
# clamp
torch.clamp(c,min = 2,max = 3)

tensor([2, 2, 2, 3, 2, 2])

####3.Reduction Operation

In [42]:
e = torch.randint(size = (2,3),low = 0,high=10,dtype = torch.float32)
e

tensor([[8., 9., 7.],
        [9., 2., 6.]])

In [45]:
print("sum",torch.sum(e))
# print(torch.sum(e,dim=0))
# print(torch.sum(e,dim=1))
print("mean",torch.mean(e))
# print(torch.mean(e,dim=0))
# print(torch.mean(e,dim=1))
print("median",torch.median(e))
# print(torch.median(e,dim=0))
# print(torch.median(e,dim=1))
print("std",torch.std(e))
# print(torch.std(e,dim=0))
# print(torch.std(e,dim=1))
print("var",torch.var(e))
# print(torch.var(e,dim=0))
# print(torch.var(e,dim=1))
print("max",torch.max(e))
# print(torch.max(e,dim=0))
# print(torch.max(e,dim=1))
print("min",torch.min(e))
# print(torch.min(e,dim=0))
# print(torch.min(e,dim=1))
print("product",torch.prod(e))
# print(torch.prod(e,dim=0))
# print(torch.prod(e,dim=1))

sum tensor(41.)
mean tensor(6.8333)
median tensor(7.)
std tensor(2.6394)
var tensor(6.9667)
max tensor(9.)
min tensor(2.)
product tensor(54432.)


###Tensor Operation On GPU

In [49]:
torch.cuda.is_available()

True

In [50]:
device = torch.device('cuda')

In [51]:
# Create a new tensor on GPU
torch.rand(2,3,device = device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [52]:
# Moving an existing tensor to GPU
a = torch.rand(2,3)
a

tensor([[0.6211, 0.5530, 0.6896],
        [0.3687, 0.9053, 0.8356]])

In [53]:
a.to(device)

tensor([[0.6211, 0.5530, 0.6896],
        [0.3687, 0.9053, 0.8356]], device='cuda:0')